package com.sentinel.aiops.service.ai;

import com.sentinel.aiops.domain.Incident;
import com.sentinel.aiops.domain.enums.Severity;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Locale;

/**
 * Offline, deterministic {@link AiProvider} strategy.
 *
 * <p>Uses lightweight heuristics so the platform delivers AI-style enrichment
 * with <b>zero external dependencies or API keys</b>. This is also the
 * graceful-degradation fallback when the remote provider's circuit breaker is
 * open — an SRE-friendly "always available, never blocks the user" design.</p>
 */
@Component
public class MockAiProvider implements AiProvider {

    @Override public String name() { return "heuristic-local"; }

    @Override public boolean isRemote() { return false; }

    @Override
    public String summarize(Incident i) {
        String svc = i.getAffectedService();
        return String.format(
            "%s is experiencing an issue: \"%s\". Reported against the %s service. " +
            "Signal indicators suggest %s impact. Recommend verifying recent deploys, " +
            "dependency health, and error-rate dashboards for %s.",
            svc, i.getTitle(), svc, severityWord(classify(i.getTitle(), i.getDescription(), i.getRawSignal())), svc);
    }

    @Override
    public Severity classifySeverity(String title, String description, String rawSignal) {
        return classify(title, description, rawSignal);
    }

    @Override
    public String suggestRootCause(Incident i) {
        String blob = blob(i.getTitle(), i.getDescription(), i.getRawSignal()).toLowerCase(Locale.ROOT);
        if (containsAny(blob, "timeout", "latency", "slow", "p99", "deadline"))
            return "Probable cause: downstream latency / saturation. Inspect connection pools, " +
                   "thread starvation, and slow dependency calls. Check recent traffic spikes.";
        if (containsAny(blob, "oom", "memory", "heap", "gc"))
            return "Probable cause: memory pressure. Inspect heap usage, GC pauses, and recent " +
                   "allocations. Consider a memory leak introduced by a recent change.";
        if (containsAny(blob, "5xx", "500", "503", "exception", "stacktrace", "npe"))
            return "Probable cause: unhandled application error. Correlate with the latest deploy; " +
                   "review error stack traces and rollback candidates.";
        if (containsAny(blob, "connection", "refused", "db", "database", "sql", "pool"))
            return "Probable cause: datastore connectivity. Verify DB health, max connections, " +
                   "network policy, and credentials rotation.";
        if (containsAny(blob, "cpu", "throttle", "load"))
            return "Probable cause: compute saturation. Inspect CPU throttling, HPA limits, and " +
                   "noisy-neighbor effects; consider scaling out.";
        return "Insufficient signal for a confident root cause. Start with the four golden signals " +
               "(latency, traffic, errors, saturation) for " + i.getAffectedService() + ".";
    }

    @Override
    public String answer(String question, List<Incident> context) {
        long open = context.stream().filter(i -> i.getResolvedAt() == null).count();
        String top = context.stream()
                .filter(i -> i.getSeverity() == Severity.SEV1)
                .map(Incident::getTitle).findFirst().orElse("none");
        return String.format(
            "Based on %d incident(s) in scope: %d are currently unresolved. " +
            "Highest-priority SEV1 item: %s. (Answer generated by the local heuristic engine — " +
            "configure a remote provider for richer natural-language answers.)",
            context.size(), open, top);
    }

    @Override
    public String generatePostmortem(Incident i, List<String> timeline) {
        StringBuilder tl = new StringBuilder();
        timeline.forEach(line -> tl.append("- ").append(line).append("\n"));
        return """
            # Postmortem: %s

            **Service:** %s  |  **Severity:** %s  |  **Status:** %s

            ## Summary
            %s

            ## Probable Root Cause
            %s

            ## Timeline
            %s
            ## Impact
            Customer-facing impact on %s while the incident was open.

            ## Action Items
            - [ ] Add/scale monitoring for the failing signal
            - [ ] Add an automated runbook step for first response
            - [ ] Review recent changes to %s for regression
            - [ ] Add alerting on the SLA breach condition

            _Generated by the local heuristic engine. Configure a remote AI provider for a richer narrative._
            """.formatted(
                i.getTitle(), i.getAffectedService(), i.getSeverity(), i.getStatus(),
                i.getAiSummary() == null ? summarize(i) : i.getAiSummary(),
                i.getAiRootCause() == null ? suggestRootCause(i) : i.getAiRootCause(),
                tl.toString().isBlank() ? "- (no timeline events recorded)\n" : tl,
                i.getAffectedService(), i.getAffectedService());
    }

    // ---- heuristics ----
    private Severity classify(String title, String description, String rawSignal) {
        String blob = blob(title, description, rawSignal).toLowerCase(Locale.ROOT);
        if (containsAny(blob, "outage", "down", "unavailable", "data loss", "breach", "all users"))
            return Severity.SEV1;
        if (containsAny(blob, "5xx", "elevated errors", "degraded", "partial", "timeout", "oom"))
            return Severity.SEV2;
        if (containsAny(blob, "slow", "warning", "minor", "intermittent"))
            return Severity.SEV3;
        return Severity.SEV4;
    }

    private static String blob(String... parts) {
        return String.join(" ", java.util.Arrays.stream(parts)
                .map(p -> p == null ? "" : p).toList());
    }

    private static boolean containsAny(String haystack, String... needles) {
        for (String n : needles) if (haystack.contains(n)) return true;
        return false;
    }

    private static String severityWord(Severity s) {
        return switch (s) {
            case SEV1 -> "critical, customer-facing";
            case SEV2 -> "major";
            case SEV3 -> "minor";
            case SEV4 -> "informational";
        };
    }
}
